### ISSUE TITLE
Review intern recommendation system related work

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/internbit#1]
The [InternBit Resources Page](https://radgrad.github.io/docs/internbit/resources) has a list of papers and tutorials on recommendation systems for internships.  

Read these papers, and then write an essay for your professional portfolio that provides:

  * A review of these resources. How can the ideas in these resources help InternBIt?
  * How will InternBit be better/different? Given that InternBit will be integrated with RadGrad, what will InternBit be able to do that these systems can't?

When the essay is published, provide a link to it as a comment to this issue. And please post the link to #summer-startup in RadGrad2 Slack.

**Comment by jhsuP** [comment]
https://jhsup.github.io/essays/internbit_resources.html

**Comment by kellikt** [comment]
https://kellikt.github.io/essays/internbit-resources.html

**Comment by auusui** [comment]
https://auusui.github.io/essays/a-piece-of-internbit.html

**Comment by miraabela** [comment]
https://miraabela.github.io/essays/internbitrw.html
