### ISSUE TITLE
Create ziprecruiter.data.json file

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/internbit#11]
Parse the ziprecruiter site, store the results in ziprecruiter.data.json

**Comment by jhsuP** [comment]
Used Puppeteer:
[data](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/ziprecruiter.data.json
) | [code](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/zipRecruiter.js) | [documentation](https://github.com/radgrad/internbit-scraper-jh-puppeteer#ziprecruiter)
