### ISSUE TITLE
Create internships.data.json file

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/internbit#15]
So, it turns out that internships.data.json file does not appear to support API access. 

Use X-Ray/Osmosis or Puppeteer to process the site, store results in internships.data.json.

**Comment by jhsuP** [comment]
[Documentation](https://github.com/radgrad/internbit-scraper-jh-puppeteer#internships-chegg) | [Data](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/internships.data.json) | [Code](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/internships.js)
