### ISSUE TITLE
Create linkedin.data.json

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/internbit#18]
Process the linkedin jobs site, put results in linkedin.data.json.

**Comment by jhsuP** [comment]
[Documentation](https://github.com/radgrad/internbit-scraper-jh-puppeteer#linkedin) | [Data](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/linkedin.data.json) | [Code](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/linkedin.js)
