### ISSUE TITLE
Create monster.data.json

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/internbit#19]
Process monster.com site. Example query:

https://www.monster.com/jobs/search/?q=computer-science-internship

Post results in monster.data.json.  If multiple queries, make multiple files.

**Comment by jhsuP** [comment]
[Documentation](https://github.com/radgrad/internbit-scraper-jh-puppeteer#monsterscom) | [Data](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/monster.data.json) | [Code](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/monster.js)
