### ISSUE TITLE
Create parser for description fields

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/internbit#20]
Use a package such as [natural](https://www.npmjs.com/package/natural) tp parse description fields and extract field info.

Generate output files like usajobs.parsed.data.json to illustrate results.

**Comment by jhsuP** [comment]
Here is my current progress: 
[Code](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/naturalTest.js) | [Data](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/linkedin.parsed.data.json)

For anyone who wishes to continue development, I added comments on my code to help.

Some additional comments:

```javascript
/// will not match "Software Engineer" or "software engineering" in general
classifier.addDocument(['software engineering'], 'software engineer');

vs.

// matches, but also classify anything with "engineer" or "software" as software engineering ("eg. Security Engineer")
classifier.addDocument('software engineering', 'software engineer');
```

The latter ends up tagging the majority of the internships as "software engineering".

It might have something to do with how the words are tokenized when it's in an array vs. just the string:

```javascript
// 'software engineer'
 doc: { label: 'software engineer', text: [ 'softwar', 'engin' ] }

vs.

// ['software engineer]
  doc: { label: 'software engineer', text: [ 'software engineering' ] }
```

It seems like there have been other issues reported: [Link #1](https://github.com/NaturalNode/natural/issues/237) | [Link #2](https://github.com/NaturalNode/natural/issues/377)

As suggested in Link #1, we may find better results writing our own tokenizers & stemmers: [Explanation](https://github.com/NaturalNode/natural/issues/441). I'm not entirely satisfied with the current results but it does the basics for now.

**Comment by kellikt** [comment]
My current progress, worked with Jenny's parser code from her previous comment:
[Code](https://github.com/radgrad/internbit-scraper-kt-puppeteer/blob/master/naturalTest.js) | [Data](https://raw.githubusercontent.com/radgrad/internbit-scraper-kt-puppeteer/master/linkedin.parsed.data.json)

Didn't feel comfortable writing a tokenizer/stemmer, so I experimented with using includes() to parse skills from the position titles. Appeared to mainly help with parsing Data Science positions, didn't seem to have a significant difference for other positions.

Also added a soft skills section. This works similarly to Jenny's parser for the regular skills, but uses a different classifier trained with soft skill keywords instead. These are added to the softSkills field for each job object.

**Comment by philipmjohnson** [comment]
@miraabela Some steps to move forward:

1. Please split the definitions of "categories" into its own file, and then import it into the file that does the parsing. (Maybe export a single object that's a data structure where keys are categories and values are arrays of strings?)

2. Here's a potential interface to the parser for use by any scraper:

```
const parser = new Parser(descriptionString);

const skills = parser.getSkills();  // returns an array of skills,  or null if nothing found.
const due = parser.getDue(); // returns the due date for applications, or null if nothing found.
const compensation = parser.getCompensation(); // returns the compensation, or null if not found.

etc.
```

The idea is that a scraper can try to get as many fields in the canonical schema as possible, then ask the parser to try to provide any remaining ones that it can.
