### ISSUE TITLE
Create canonical schema and convert files

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/internbit#21]
Analyze data.json files, create canonical representation, convert existing files.

Create files like usajobs.canonical.data.json to represent the results.

**Comment by jhsuP** [comment]
Possible template:
```json
[
    {
        "position": "",
        "company": "",
        "location": "",
        "URL": "",
        "skills": "",
        "lastScraped": "",
        "description": ""
    },
]

**Comment by miraabela** [comment]
[Glassdoor](https://github.com/radgrad/internbit-scraper-mm-xray/blob/master/glassdoor.canonical.data.json)

[Cheerio](https://github.com/radgrad/internbit-scraper-mm-cheerio/blob/master/indeed.canonical.data.json)

**Comment by jhsuP** [comment]
[LinkedIn](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/linkedin.canonical.data.json)
[Internships (Chegg)](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/internships.canonical.data.json)
[Monster](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/monster.canonical.data.json)
[SimplyHired](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/simplyHired.canonical.data.json)
[ZipRecruiter](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/ziprecruiter.canonical.data.json)

**Comment by auusui** [comment]
[Youtern](https://github.com/radgrad/internbit-scraper-au-Youtern/blob/master/youtern.canonical.data.json)
[CoolWorks](https://raw.githubusercontent.com/radgrad/internbit-scraper-au-Youtern/master/CoolWorks.canonical.data.json)

**Comment by kellikt** [comment]
[Idealist](https://github.com/radgrad/internbit-scraper-kt-puppeteer/blob/master/idealist.canonical.data.json)
[Student Opportunity Center](https://github.com/radgrad/internbit-scraper-kt-puppeteer/blob/master/soc.canonical.data.json)

**Comment by philipmjohnson** [comment]
The following files conform to the "new" canonical format I defined today:

[Internships.com  (Chegg)](https://github.com/radgrad/internbit-scraper-pj-superagent/blob/master/internshipsdotcom.canonical.data.json) (This was probably a waste of time since we need to scrape the site via Jenny's code.)

[NSF REU](https://github.com/radgrad/internbit-scraper-pj-superagent/blob/master/nsf-reu.canonical.data.json)

[USA Jobs (Internship keyword)](https://github.com/radgrad/internbit-scraper-pj-superagent/blob/master/usajobs.internship.canonical.data.json)

[USA Jobs (Software keyword)](https://github.com/radgrad/internbit-scraper-pj-superagent/blob/master/usajobs.software.canonical.data.json)

**Comment by kellikt** [comment]
These files conform to the new canonical format:

[Idealist](https://github.com/radgrad/internbit-scraper-kt-puppeteer/blob/master/idealist.canonical.data.json)
[SOC](https://github.com/radgrad/internbit-scraper-kt-puppeteer/blob/master/soc.canonical.data.json)

**Comment by jhsuP** [comment]
These files have been fixed and conform to the updated format:

[LinkedIn](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/linkedin.canonical.data.json)
[Internships (Chegg)](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/internships.canonical.data.json)
[Monster](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/monster.canonical.data.json)
[SimplyHired](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/simplyHired.canonical.data.json)
[ZipRecruiter](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/ziprecruiter.canonical.data.json)
