### ISSUE TITLE
Create acm.canonical.data.json

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/internbit#29]
See: https://jobs.acm.org/jobs/results/keyword/internship

Note that a lot of the hits aren't internships, I had to scroll to the second page to find any. So, some post-processing may be necessary to filter out the bad hits.

**Comment by jhsuP** [comment]
A potentially better link that only shows internships: https://jobs.acm.org/jobs/results/title/Internship/United+States?radius=5

**Comment by ruizaj** [comment]
I was mostly able to make an acm scraper and the acm.canonical.data.json file.
