### ISSUE TITLE
Add resource(s) to Resource page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/internbit#3]
Look for relevant readings, and add to https://radgrad.github.io/docs/internbit/resources

This task will require you to download the RadGrad Summer 2020 docusaurus repo, edit the file, run the system locally to ensure your modifications are OK, then deploy it, as well as commit your changes to the docusaurus2 repo. See https://radgrad.github.io/docs/overview/managing-this-site

This task is not only helpful for generating additional useful resources, it's also good for getting you ready to contribute documentation.

When you're done, add a comment to this issue summarizing what resources you added.

**Comment by miraabela** [comment]
I added a link to my techreport to the Resources page, but I don't have write access to the repo

**Comment by auusui** [comment]
added link of intro to the recommended system

**Comment by kellikt** [comment]
I added links to [How to build a simple web crawler]https://towardsdatascience.com/how-to-build-a-simple-web-crawler-66082fc82470 and [Recommender systems]https://builtin.com/data-science/recommender-systems.

The first link is a tutorial on building a web crawler, I felt that this would be useful to read through as a supplement to the brief web crawler section in [Building an internship recommendation system](https://medium.com/@ishannangia/building-an-internship-recommendation-system-i-introduction-8ab428131483). It goes through the process step-by-step and also has a link to the repository for their python web crawler.

The second link goes through different types of recommendation systems (collaborative and content-based, also includes a hybrid model), how to implement them, and provides a repository with some example code for both types of recommendation systems.

**Comment by jhsuP** [comment]
Added 2 links:
Building Web Scraper using Javascript
Simple Web Scraping with Node.js and Javascript

Since RadGrad is written in Javascript, I thought it would be important to have some readings on how to implement a Web Scaper using Javascript since the others used python.
