### ISSUE TITLE
Review intern recommendation system related work

### ISSUE THREAD

**Issue by jhsuP** [radgrad/internbit#33]
To gain a sense of what we want to accomplish for InternBit, review the links on [InternBit Resource](https://radgrad.github.io/docs/subprojects/internbit/resources). Particularly, Mirabela's [research proposal](http://csdl.ics.hawaii.edu/techreports/2020/20-04/20-04.pdf) is important as it outlines what we envision. Jot down any questions you may have so we can discuss it. Since this is a shared issue, once you're done you can comment "done" and the last person can close the issue.

**Comment by ruizaj** [comment]
Done
