### ISSUE TITLE
Review Puppeteer 

### ISSUE THREAD

**Issue by jhsuP** [radgrad/internbit#34]
For web scraping, we mainly use [Puppeteer](https://pptr.dev/#?product=Puppeteer&version=v4.0.0&show=api-class-puppeteer). You can look over the docs and watch some YouTube videos on how it works. I personally used [this](https://www.youtube.com/watch?v=IvaJ5n5xFqU&t=1408s&ab_channel=optikalefx) and it was very helpful. Since this is a shared issue, once you're done you can comment "done" and the last person can close the issue.

**Comment by ruizaj** [comment]
Done
