### ISSUE TITLE
Level Up in RadGrad

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/internbit#4]
To be an effective member of the RadGrad project, it's important to be a user. 

For this task, please figure out what is necessary to make it to the next Level in RadGrad, then do it. 

Once you've achieved your new Level, write an essay for your professional portfolio about your experience. What did you find useful about RadGrad while trying to Level Up? Did you discover new features or information that you were not aware of before?  What do you wish RadGrad had that it does not currently have?  What changes would you advise in order to make RadGrad more useful to undergraduates at UH?

When you've finished your essay, please post a link to it as a comment to this issue. And please post the link to #summer-startup in RadGrad2 Slack.

**Comment by miraabela** [comment]
Requested verification for a bunch of opportunities

**Comment by kellikt** [comment]
https://kellikt.github.io/essays/experiencing-radgrad.html

**Comment by jhsuP** [comment]
https://jhsup.github.io/essays/radgrad.html

**Comment by auusui** [comment]
https://auusui.github.io/essays/radgrad-level-up.html
