### ISSUE TITLE
Condense Companies Dropdown

### ISSUE THREAD

**Issue by jhsuP** [radgrad/internbit#41]
Duplicate companies show in dropdown:
![image](https://user-images.githubusercontent.com/56209781/94208547-ca746880-fe65-11ea-981a-90adfc8e919f.png)

Figure out a way during parsing of company to catch the different ways they are listed and condense to one.

**Comment by ruizaj** [comment]
I made a functional search bar for the companies filter, but I'll leave this at in-progress for further checking
