### ISSUE TITLE
Research different models of recommendation systems

### ISSUE THREAD

**Issue by jhsuP** [radgrad/internbit#64]
There are different models for recommendation systems. Here are some examples:

- Collaborative Filtering based
- Content-based

Research on the different types and  write an essay for your professional portfolio that provides:
- Review of the different types of recommendation systems
- Pick which model you think fits best for what InternBit is trying to accomplish and explain why

When you're done, post the link in #internbit-chat so others can give input. The point of this is so we can hone down on which model of recommendation system we want to focus on before we actually try to implement one.

**Comment by jhsuP** [comment]
https://jhsup.github.io/blog/recommendation-systems

**Comment by ruizaj** [comment]
https://ruizaj.github.io/essays/recommendations.html
