### ISSUE TITLE
Evaluate remote pair programming

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/internbit#7]
First, review http://radgrad.github.io/docs/overview/remote-pair-programming

Next, practice remote pair programming with a technology of your choice at least three times during the next week. Each session should last at least 20 minutes. You can work with just one person for all three sessions if that makes most sense, or pick a different person for each session if that sounds more useful.

Finally, write an essay for your portfolio detailing your initial experiences doing remote pair programming:

* Describe each session: who you worked with, what you worked on, how long you worked, what technology you used.
* For each session, what worked well? What problems did you encounter?
* Upon reflection, what are your initial recommendations for how to perform remote pair programming successfully based upon your experiences?

Post the URL to your essay as a comment to this issue, and also post the URL to the #summer-students channel in Slack.

**Comment by auusui** [comment]
https://auusui.github.io/essays/remote-pairing-program.html

**Comment by jhsuP** [comment]
https://jhsup.github.io/essays/pair-programming.html

**Comment by kellikt** [comment]
Sorry! Completed this essay last week, but forgot to post it here: https://kellikt.github.io/essays/two-brains.html
